<a href="https://colab.research.google.com/github/yesaswanimuppidi-hash/YASASWINI/blob/main/REM_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**REMOVING DUPLICATES**

Import Libraries

In [1]:
import pandas as pd

Load Excel File

In [2]:
df = pd.read_excel("/content/sample_data/LIBRARY DATA SET.xlsx")
print(df.shape)
df.head()

(200, 10)

,Book_ID,Title,Author,Category,Cabinet,Rack,Row,Signal_Strength,Timestamp,Status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out
3,B004,The Chronicles of Dream,Casey Walker,Fiction,4,1,1,-60,2024-12-11 10:04:00,Missing
4,B005,The Future of Adventures,Skyler Lee,Programming,3,4,2,-58,2024-12-11 10:05:00,Missing

Check Duplicate Rows

In [3]:
duplicates = df.duplicated()
print(duplicates.sum())

0

View Duplicate Records

In [4]:
df[df.duplicated()]

Empty DataFrame
Columns: [Book_ID, Title, Author, Category, Cabinet, Rack, Row, Signal_Strength, Timestamp, Status]
Index: []

Remove Full Duplicate Rows

In [5]:
df_clean = df.drop_duplicates()
print(df_clean.shape)

(200, 10)

Save Clean Data

In [6]:
df_clean.to_excel("LIBRARY_DATA_CLEAN.xlsx", index=False)
print("Duplicates removed and file saved successfully!")

Duplicates removed and file saved successfully!